### ISSUE TITLE
All page links on the blog are broken

### ISSUE THREAD

**Issue by iammeat** [USBGuard/usbguard.github.io#1]
While browsing for more information regarding installing USBGuard on Ubuntu 14.04, I found that all links on [this page](https://usbguard.github.io/blog/) are broken.  For example, instead of linking to [https://usbguard.github.io/blog/2017/Screen-Locking](https://usbguard.github.io/blog/2017/Screen-Locking), they link to [https://blog/2017/Screen-Locking](https://blog/2017/Screen-Locking), which does not exist.

**Comment by dkopecek** [comment]
Thanks! I've finally found out what was causing the issue and fixed it.
